import { BroadcastTemplateMeta } from "./types.js";

export const BROADCAST_TEMPLATES_REGISTRY: BroadcastTemplateMeta[] = [
  {
    id: "lower-third.standard",
    name: "Standart Alt Bant (Lower-Third)",
    category: "LOWER-THIRD",
    description: "İsim, ünvan, konu ve kategori rozeti içeren standart haber alt bandı.",
    channel: 1,
    layer: 20,
    cgLayer: 10,
    inDuration: 0.6,
    outDuration: 0.4,
    defaultData: {
      title: "Ahmet Yılmaz",
      subtitle: "Haber Spikeri • Canlı Yayın",
      category: "HABER ÖZEL",
      accent: "#C8102E",
    },
    fields: [
      { key: "title", label: "İsim / Ana Başlık", type: "string", defaultVal: "Ahmet Yılmaz" },
      { key: "subtitle", label: "Ünvan / Açıklama", type: "string", defaultVal: "Haber Spikeri • Canlı Yayın" },
      { key: "category", label: "Kategori Rozeti", type: "string", defaultVal: "HABER ÖZEL" },
      { key: "accent", label: "Vurgu Rengi", type: "color", defaultVal: "#C8102E" },
    ],
    thumbnailUrl: "/templates/lower-third.standard/thumb.png",
  },
  {
    id: "lower-third.social",
    name: "Sosyal Medya & Alıntı Alt Bandı",
    category: "LOWER-THIRD",
    description: "X (Twitter), Telegram ve YouTube hesap veya paylaşım alıntı bandı.",
    channel: 1,
    layer: 20,
    cgLayer: 11,
    inDuration: 0.5,
    outDuration: 0.4,
    defaultData: {
      platform: "X (Twitter)",
      handle: "@haber_merkezi",
      quote: "Bölgedeki son gelişmeler canlı yayında değerlendiriliyor.",
      accent: "#1DA1F2",
    },
    fields: [
      { key: "platform", label: "Platform", type: "select", defaultVal: "X (Twitter)", options: ["X (Twitter)", "Telegram", "YouTube", "Instagram"] },
      { key: "handle", label: "Kullanıcı Adı / Hesap", type: "string", defaultVal: "@haber_merkezi" },
      { key: "quote", label: "Paylaşım Metni", type: "string", defaultVal: "Bölgedeki son gelişmeler canlı yayında değerlendiriliyor." },
      { key: "accent", label: "Platform Rengi", type: "color", defaultVal: "#1DA1F2" },
    ],
    thumbnailUrl: "/templates/lower-third.social/thumb.png",
  },
  {
    id: "lower-third.quote",
    name: "Açıklama & Beyanat Kutusu",
    category: "LOWER-THIRD",
    description: "Önemli açıklamalar ve doğrudan alıntılar için tırnak işaretli şık konuşma kartı.",
    channel: 1,
    layer: 20,
    cgLayer: 14,
    inDuration: 0.6,
    outDuration: 0.4,
    defaultData: {
      speaker: "Devlet Yetkilisi",
      statement: "Yatırımlarımız kararlılıkla devam edecek, yeni projeler yolda.",
      source: "Basın Toplantısı",
      accent: "#EAB308",
    },
    fields: [
      { key: "speaker", label: "Açıklamayı Yapan", type: "string", defaultVal: "Devlet Yetkilisi" },
      { key: "statement", label: "Açıklama / Beyanat", type: "string", defaultVal: "Yatırımlarımız kararlılıkla devam edecek, yeni projeler yolda." },
      { key: "source", label: "Kaynak / Etkinlik", type: "string", defaultVal: "Basın Toplantısı" },
      { key: "accent", label: "Vurgu Rengi", type: "color", defaultVal: "#EAB308" },
    ],
    thumbnailUrl: "/templates/lower-third.quote/thumb.png",
  },
  {
    id: "ticker.headline",
    name: "Kayan Haber Bandı (Headline Ticker)",
    category: "TICKER",
    description: "Ekran altında kesintisiz akan haber bandı ve acil flaş haber rozeti.",
    channel: 1,
    layer: 20,
    cgLayer: 20,
    inDuration: 0.5,
    outDuration: 0.4,
    defaultData: {
      category: "SON DAKİKA",
      items: ["MCR Yayın Otomasyonu devrede.", "Hazar kıyısında yeni enerji anlaşması imzalandı."],
      speed: 120,
    },
    fields: [
      { key: "category", label: "Kategori Başlığı", type: "string", defaultVal: "SON DAKİKA" },
      { key: "speed", label: "Kayma Hızı (px/s)", type: "number", defaultVal: 120 },
    ],
    thumbnailUrl: "/templates/ticker.headline/thumb.png",
  },
  {
    id: "ticker.finance",
    name: "Finans & Piyasa Bandı (Finance Ticker)",
    category: "TICKER",
    description: "Dolar, Euro, Altın, Petrol ve Borsa endekslerinin canlı değişim oranları bandı.",
    channel: 1,
    layer: 20,
    cgLayer: 21,
    inDuration: 0.5,
    outDuration: 0.4,
    defaultData: {
      usd: "3.50",
      usdChange: "+0.12%",
      eur: "3.80",
      eurChange: "-0.05%",
      gold: "2,450$",
      goldChange: "+1.20%",
      brent: "82.40$",
      brentChange: "+0.45%",
    },
    fields: [
      { key: "usd", label: "USD/TMT", type: "string", defaultVal: "3.50" },
      { key: "usdChange", label: "USD Değişim", type: "string", defaultVal: "+0.12%" },
      { key: "eur", label: "EUR/TMT", type: "string", defaultVal: "3.80" },
      { key: "eurChange", label: "EUR Değişim", type: "string", defaultVal: "-0.05%" },
      { key: "gold", label: "Ons Altın", type: "string", defaultVal: "2,450$" },
      { key: "brent", label: "Brent Petrol", type: "string", defaultVal: "82.40$" },
    ],
    thumbnailUrl: "/templates/ticker.finance/thumb.png",
  },
  {
    id: "breaking-news.stinger",
    name: "Son Dakika Stinger (Fullscreen)",
    category: "STINGER",
    description: "Tam ekran kırmızı/koyu animasyonlu flaş haber geçiş stinger'ı.",
    channel: 1,
    layer: 30,
    cgLayer: 5,
    inDuration: 0.8,
    outDuration: 0.6,
    defaultData: {
      title: "SON DAKİKA GELİŞMESİ",
      subtitle: "MCR HABER MERKEZİ BİLDİRİYOR",
      accent: "#EF4444",
    },
    fields: [
      { key: "title", label: "Flaş Başlık", type: "string", defaultVal: "SON DAKİKA GELİŞMESİ" },
      { key: "subtitle", label: "Alt Metin", type: "string", defaultVal: "MCR HABER MERKEZİ BİLDİRİYOR" },
      { key: "accent", label: "Ana Renk", type: "color", defaultVal: "#EF4444" },
    ],
    thumbnailUrl: "/templates/breaking-news.stinger/thumb.png",
  },
  {
    id: "score-bug.sports",
    name: "Spor Skor Tablosu (Score Bug)",
    category: "SCORE-BUG",
    description: "Canlı maç skoru, takım isimleri, maç süresi ve devre bilgisi tablosu.",
    channel: 1,
    layer: 20,
    cgLayer: 15,
    inDuration: 0.5,
    outDuration: 0.4,
    defaultData: {
      teamA: "AHL",
      scoreA: 2,
      teamB: "KOP",
      scoreB: 1,
      matchTime: "74:20",
      period: "2. DEVRE",
    },
    fields: [
      { key: "teamA", label: "Ev Sahibi Takım", type: "string", defaultVal: "AHL" },
      { key: "scoreA", label: "Ev Sahibi Skor", type: "number", defaultVal: 2 },
      { key: "teamB", label: "Deplasman Takım", type: "string", defaultVal: "KOP" },
      { key: "scoreB", label: "Deplasman Skor", type: "number", defaultVal: 1 },
      { key: "matchTime", label: "Maç Süresi", type: "string", defaultVal: "74:20" },
      { key: "period", label: "Devre", type: "string", defaultVal: "2. DEVRE" },
    ],
    thumbnailUrl: "/templates/score-bug.sports/thumb.png",
  },
  {
    id: "weather-card.info",
    name: "Hava Durumu Kartı (Weather Card)",
    category: "WEATHER-CARD",
    description: "Şehir sıcaklığı, rüzgar, nem ve 5 günlük tahmin kartı.",
    channel: 1,
    layer: 20,
    cgLayer: 12,
    inDuration: 0.6,
    outDuration: 0.4,
    defaultData: {
      city: "AŞKABAT",
      temp: "32°C",
      condition: "Güneşli ve Açık",
      humidity: "%28",
      wind: "14 km/s KB",
    },
    fields: [
      { key: "city", label: "Şehir İsmi", type: "string", defaultVal: "AŞKABAT" },
      { key: "temp", label: "Sıcaklık", type: "string", defaultVal: "32°C" },
      { key: "condition", label: "Hava Durumu", type: "string", defaultVal: "Güneşli ve Açık" },
      { key: "humidity", label: "Nem Oranı", type: "string", defaultVal: "%28" },
      { key: "wind", label: "Rüzgar Hızı", type: "string", defaultVal: "14 km/s KB" },
    ],
    thumbnailUrl: "/templates/weather-card.info/thumb.png",
  },
  {
    id: "side-panel.bullet-points",
    name: "Gündem Maddeleri Yan Panel",
    category: "SIDE-PANEL",
    description: "Ekranın sağında açılan 3 maddelik canlı analiz ve gündem infografiği.",
    channel: 1,
    layer: 20,
    cgLayer: 16,
    inDuration: 0.7,
    outDuration: 0.5,
    defaultData: {
      mainHeader: "ZİRVEDE ÖNE ÇIKANLAR",
      point1: "1. Enerji koridorunda yeni stratejik ortaklıklar",
      point2: "2. Hazar geçişli ticaret hacminde %40 artış",
      point3: "3. Ortak altyapı projeleri onaylandı",
      accent: "#3B82F6",
    },
    fields: [
      { key: "mainHeader", label: "Ana Başlık", type: "string", defaultVal: "ZİRVEDE ÖNE ÇIKANLAR" },
      { key: "point1", label: "Madde 1", type: "string", defaultVal: "1. Enerji koridorunda yeni stratejik ortaklıklar" },
      { key: "point2", label: "Madde 2", type: "string", defaultVal: "2. Hazar geçişli ticaret hacminde %40 artış" },
      { key: "point3", label: "Madde 3", type: "string", defaultVal: "3. Ortak altyapı projeleri onaylandı" },
      { key: "accent", label: "Vurgu Rengi", type: "color", defaultVal: "#3B82F6" },
    ],
    thumbnailUrl: "/templates/side-panel.bullet-points/thumb.png",
  },
  {
    id: "split-screen.two-box",
    name: "İkili Canlı Bağlantı Çerçevesi (2-Box)",
    category: "SPLIT-SCREEN",
    description: "Stüdyo ve saha muhabiri ikili canlı yayın çerçevesi ve alt etiketleri.",
    channel: 1,
    layer: 20,
    cgLayer: 17,
    inDuration: 0.6,
    outDuration: 0.4,
    defaultData: {
      boxLeftLabel: "STÜDYO • AŞKABAT",
      boxRightLabel: "CANLI BAĞLANTI • TÜRKMENBAŞI",
      topic: "HAZAR LİMANI CANLI YAYIN",
    },
    fields: [
      { key: "boxLeftLabel", label: "Sol Kutu Etiketi", type: "string", defaultVal: "STÜDYO • AŞKABAT" },
      { key: "boxRightLabel", label: "Sağ Kutu Etiketi", type: "string", defaultVal: "CANLI BAĞLANTI • TÜRKMENBAŞI" },
      { key: "topic", label: "Bağlantı Konusu", type: "string", defaultVal: "HAZAR LİMANI CANLI YAYIN" },
    ],
    thumbnailUrl: "/templates/split-screen.two-box/thumb.png",
  },
  {
    id: "fullscreen.bumper",
    name: "Program Jeneriği & Bumper",
    category: "BUMPER",
    description: "Bölüm geçişleri, program açılışları ve ara tanıtımlar için şık animasyonlu kart.",
    channel: 1,
    layer: 30,
    cgLayer: 8,
    inDuration: 0.8,
    outDuration: 0.6,
    defaultData: {
      programTitle: "GÜNDEM ÖZEL",
      episodeSubtitle: "BÖLGE EKONOMİSİ VE ENERJİ HATTI",
      hostName: "SUNUCU: AHMET YILMAZ",
    },
    fields: [
      { key: "programTitle", label: "Program Adı", type: "string", defaultVal: "GÜNDEM ÖZEL" },
      { key: "episodeSubtitle", label: "Bölüm / Konu", type: "string", defaultVal: "BÖLGE EKONOMİSİ VE ENERJİ HATTI" },
      { key: "hostName", label: "Sunucu / Yapımcı", type: "string", defaultVal: "SUNUCU: AHMET YILMAZ" },
    ],
    thumbnailUrl: "/templates/fullscreen.bumper/thumb.png",
  },
];

export function getTemplateById(id: string): BroadcastTemplateMeta | undefined {
  return BROADCAST_TEMPLATES_REGISTRY.find((t) => t.id === id);
}

export function getTemplatesByCategory(category: string): BroadcastTemplateMeta[] {
  return BROADCAST_TEMPLATES_REGISTRY.filter((t) => t.category === category);
}

export function getAllTemplates(): BroadcastTemplateMeta[] {
  return BROADCAST_TEMPLATES_REGISTRY;
}
